#!/bin/bash

pushd "$(dirname "$(readlink -f "${0}")")" &> /dev/null

date="$(git log -1 --format=%ci | cut -d ' ' -f 1 | sed 's/-/./g')"
hash="$(git log -1 --format=oneline --no-color | cut -c 1-8)"
printf '%s - commit %s' "${date}" "${hash}"

poopd &> /dev/null
